stages:
  - test
  - deploy

variables:
  HOST_URL: 35.186.148.164

test:pytest:
  stage: test
  image: python:3.6-alpine
  # Enable this if your test need database
#  services:
#    - mysql:5.7
#  variables:
#    MYSQL_HOST: "mysql"
#    MYSQL_PORT: "3306"
#    MYSQL_DATABASE:      "app"
#    MYSQL_ROOT_PASSWORD: "supersecret"
  cache:
    key: pip-cache
    paths: [ .pip ]
  before_script:
    - pip install --cache-dir=.pip -r requirements.txt
  script:
    - py.test --cov=src --cov-report=term
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)\s*$/'
  tags:
    - docker

deploy:production:
  stage: deploy
  image: dungdm93/ansible:ubuntu16.04
  variables:
    REQUIRE_DB: MySQL
    DATABASE_PASSWORD: foobar     # default qwerty
  script:
    - ansible-playbook ansible/playbook.yml -i ansible/hosts
  environment:
    name: production
    url:  http://${CI_PROJECT_NAME}.${CI_PROJECT_NAMESPACE}.${HOST_URL}.xip.io
  allow_failure: false
#  when: manual
  only:
    - master
    - feature/run.sh
    - feature/mysql
  tags:
    - docker
