stages:
  - test
  - deploy

#debug:
#  stage: test
#  variables:
#    CI_DEBUG_TRACE: "true"
#  script:
#    - echo "Hello world"
#  tags:
#    - docker

#test:pytest:
#  stage: test
#  image: python:3.6-alpine
#  services:
#    - mysql:5.7
#  variables:
#    MYSQL_HOST: "mysql"
#    MYSQL_PORT: "3306"
#    MYSQL_DATABASE:      "app"
#    MYSQL_ROOT_PASSWORD: "supersecret"
#  cache:
#    key: pip-cache
#    paths: [ .pip ]
#  before_script:
#    - pip install --cache-dir=.pip -r requirements.txt
#  script:
#    - py.test --cov=src --cov-report=term
#  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)\s*$/'
#  tags:
#    - docker

deploy:production:
  stage: deploy
  image: dungdm93/ansible:ubuntu16.04
  script:
    - envsubst < etc/supervisor.d/supervisor-worker.conf.temp > etc/supervisor.d/supervisor-worker.conf
    - envsubst < etc/nginx-sites.conf.temp                    > etc/nginx-sites.conf
    - envsubst < instance/config.py.temp                      > instance/config.py
    - ansible-playbook ansible/playbook.yml -i ansible/hosts
#  environment:
#    name: production
#    url:  prod.teko.vn
#  allow_failure: false
#  when: manual
  only:
    - master
  tags:
    - docker
