---
- hosts: production
  vars:
    username: "{{ lookup('env', 'CI_PROJECT_NAMESPACE') }}"
    app_name: "{{ lookup('env', 'CI_PROJECT_NAME') }}"
    app_repo: "{{ lookup('env', 'CI_PROJECT_URL') }}"
    app_root: "/home/{{ username }}/{{ app_name }}"

  tasks:
  - name: Create user
    user:
      name:    "{{username}}"
      comment: "Gitlab-CI auto-create user"
      group:   admin
      shell:   /bin/bash

  - name: Checkout repository
    become: yes
    become_user: "{{username}}"
    git:
      repo: "{{app_repo}}"
      dest: "{{app_root}}"
      force: true
      accept_hostkey: true
      version: "{{ lookup('env', 'CI_COMMIT_SHA') | default('HEAD', true) }}"
#    notify:
#    - restart app

  - name: Install pip dependencies
    become: yes
    become_user: "{{username}}"
    pip:
      chdir: "{{app_root}}"
      requirements: "./requirements.txt"
      virtualenv:   "{{app_root}}/.venv"
      virtualenv_python: python3.6
#    notify:
#    - restart app

  - name: Copy app config
    become: yes
    become_user: "{{username}}"
    copy:
      src:  "../instance/config.py"
      dest: "{{app_root}}/instance/config.py"
      force: yes
#    notify:
#    - restart app

  handlers:
  - name: restart nginx
    become: yes
    service: name=nginx state=restarted

  - name: restart app
    shell: |
      source .venv/bin/activate
      supervisorctl reread
      supervisorctl restart foobar
    args:
      chdir: "{{app_root}}"
      executable: /bin/bash
