---
# Login user as `root`
- hosts: production
  vars:
    username: "{{ lookup('env', 'CI_PROJECT_NAMESPACE') }}"
    app_name: "{{ lookup('env', 'CI_PROJECT_NAME') }}"
    app_repo: "{{ lookup('env', 'CI_PROJECT_URL') }}"
    app_root: "/home/{{ username }}/{{ app_name }}"

  tasks:
  - name: Create user
    user:
      name:    "{{username}}"
      comment: "Gitlab-CI auto-create user"
      group:   admin
      shell:   /bin/bash

  - name: Checkout repository
    become: yes
    become_user: "{{username}}"
    git:
      repo: "{{app_repo}}"
      dest: "{{app_root}}"
      force: true
      accept_hostkey: true
      version: "{{ lookup('env', 'CI_COMMIT_SHA') | default('HEAD', true) }}"
#    notify:
#    - restart app

  - name: Install pip dependencies
    become: yes
    become_user: "{{username}}"
    pip:
      chdir: "{{app_root}}"
      requirements: "./requirements.txt"
      virtualenv:   "{{app_root}}/.venv"
      virtualenv_python: python3.6
#    notify:
#    - restart app

  - name: Config app
    become: yes
    become_user: "{{username}}"
    copy:
      src:  "../instance/config.py"
      dest: "{{app_root}}/instance/config.py"
      force: yes
#    notify:
#    - restart app

  - name: Config supervisor
    copy:
      src:  "files/supervisor-worker.conf"
      dest: "/etc/supervisor/conf.d/{{username}}-{{app_name}}.conf"
      force: yes
    notify:
    - restart app

  - name: Config nginx
    copy:
      src:  "files/nginx-sites.conf"
      dest: "/etc/nginx/sites-enabled/{{username}}-{{app_name}}.conf"
      force: yes
#    notify:
#    - restart nginx

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted

  # ===== SETUP INSTRUCTIONS =====
  # Disable supervisor service
  # $ sudo systemctl disable supervisor
  # Run supervisor manually with command:
  # $ supervisord
  # ==============================
  - name: restart app
    shell: |
      set -e
      if [ ! -f "/run/supervisor.sock" ]; then
        supervisord
      fi
      source .venv/bin/activate
      supervisorctl reread
      supervisorctl restart {{username}}@{{app_name}}:*
    args:
      chdir: "{{app_root}}"
      executable: /bin/bash
